services:
  app:
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    # default command is "npm start" from the dev stage

  test:
    build:
      context: .
      target: dev
    command: ["npm","test"]
    profiles: ["test"]

  lint:
    build:
      context: .
      target: dev
    command: ["npm","run","lint"]
    profiles: ["lint"]

  audit:
    build:
      context: .
      target: dev
    command: ["npm","audit","--audit-level=high"]
    profiles: ["audit"]
